
from typing import Dict, Any, List

CHEST_COIN_RANGE = [1000, 5000]

CHEST_REWARDS: List[Dict[str, Any]] = [
    {"item": "Blood rune", "min": 3, "max": 20, "chance": "1/2"},
    {"item": "Revenant ether", "min": 30, "max": 50, "chance": "1/3"},
    {"item": "Rune platebody", "min": 1, "max": 1, "chance": "1/10"},
    {"item": "Dragon dagger", "min": 1, "max": 1, "chance": "1/50"},
    {"item": "Dragon platebody", "min": 1, "max": 1, "chance": "1/100"},
    {"item": "Dragon boots", "min": 1, "max": 1, "chance": "1/75"},
]

SHOP_ITEMS: Dict[str, int] = {
    "Starter Sword": 0,
    "Starter Platebody": 0,
    "Mysterious key": 100000,
    "Strength (4)": 5000,
    "Lobster": 1000,
    "Shark": 2000,
    "Bronze arrows": 500,
    "Iron arrows": 1500,
    "Air rune": 500,
    "Water rune": 500,
    "Earth rune": 500,
    "Fire rune": 750,
    "Rotwood shortbow": 5000,
    "Galestaff": 5000,
}

LOOT_TABLES: Dict[str, List[Dict[str, Any]]] = {
    "shallow": [ # <=10
        {"item": "Nature rune", "min": 1, "max": 3, "chance": "1/2"},
        {"item": "Law rune", "min": 1, "max": 2, "chance": "1/2"},
        {"item": "Lobster", "min": 1, "max": 4, "chance": "1/2"},
        {"item": "Shark", "min": 1, "max": 2, "chance": "1/6"},
        {"item": "Rune scimitar", "min": 1, "max": 1, "chance": "1/50"},
        {"item": "Rune chainbody", "min": 1, "max": 1, "chance": "1/80"},
        {"item": "Rune med helm", "min": 1, "max": 1, "chance": "1/40"},
        {"item": "Rune sq shield", "min": 1, "max": 1, "chance": "1/45"},
        {"item": "Air rune", "min": 3, "max": 10, "chance": "1/3"},
        {"item": "Water rune", "min": 3, "max": 10, "chance": "1/3"},
        {"item": "Earth rune", "min": 2, "max": 8, "chance": "1/4"},
        {"item": "Fire rune", "min": 2, "max": 6, "chance": "1/5"},
        {"item": "Bronze arrows", "min": 5, "max": 20, "chance": "1/3"},
        {"item": "Iron arrows", "min": 3, "max": 10, "chance": "1/5"},
    ],
    "mid": [ # <=20
        {"item": "Nature rune", "min": 2, "max": 10, "chance": "1/2"},
        {"item": "Law rune", "min": 2, "max": 10, "chance": "1/2"},
        {"item": "Rune scimitar", "min": 1, "max": 1, "chance": "1/25"},
        {"item": "Rune chainbody", "min": 1, "max": 1, "chance": "1/60"},
        {"item": "Rune med helm", "min": 1, "max": 1, "chance": "1/30"},
        {"item": "Rune sq shield", "min": 1, "max": 1, "chance": "1/35"},
        {"item": "Death rune", "min": 5, "max": 25, "chance": "1/2"},
        {"item": "Blood rune", "min": 3, "max": 20, "chance": "1/2"},
        {"item": "Shark", "min": 1, "max": 4, "chance": "1/2"},
        {"item": "Shark", "min": 4, "max": 8, "chance": "1/20", "noted": True},
        {"item": "Rune platebody", "min": 1, "max": 1, "chance": "1/80"},
        {"item": "Rune platelegs", "min": 1, "max": 1, "chance": "1/80"},
        {"item": "Rune full helm", "min": 1, "max": 1, "chance": "1/80"},
        {"item": "Dragon dagger", "min": 1, "max": 1, "chance": "1/120"},
        {"item": "Air rune", "min": 5, "max": 20, "chance": "1/3"},
        {"item": "Water rune", "min": 5, "max": 20, "chance": "1/3"},
        {"item": "Earth rune", "min": 5, "max": 15, "chance": "1/3"},
        {"item": "Fire rune", "min": 3, "max": 12, "chance": "1/4"},
        {"item": "Iron arrows", "min": 5, "max": 20, "chance": "1/3"},
        {"item": "Steel arrows", "min": 3, "max": 10, "chance": "1/5"},
        {"item": "Mithril arrows", "min": 2, "max": 8, "chance": "1/8"},
    ],
    "deep": [ # <=35
        {"item": "Nature rune", "min": 10, "max": 50, "chance": "1/2"},
        {"item": "Law rune", "min": 10, "max": 60, "chance": "1/2"},
        {"item": "Rune scimitar", "min": 1, "max": 1, "chance": "1/5"},
        {"item": "Rune chainbody", "min": 1, "max": 1, "chance": "1/10"},
        {"item": "Rune med helm", "min": 1, "max": 1, "chance": "1/15"},
        {"item": "Rune sq shield", "min": 1, "max": 1, "chance": "1/20"},
        {"item": "Death rune", "min": 40, "max": 100, "chance": "1/2"},
        {"item": "Rune platebody", "min": 1, "max": 1, "chance": "1/50"},
        {"item": "Rune platelegs", "min": 1, "max": 1, "chance": "1/50"},
        {"item": "Rune full helm", "min": 1, "max": 1, "chance": "1/50"},
        {"item": "Dragon dagger", "min": 1, "max": 1, "chance": "1/70"},
        {"item": "Blood rune", "min": 20, "max": 90, "chance": "1/2"},
        {"item": "Shark", "min": 2, "max": 10, "chance": "1/2"},
        {"item": "Shark", "min": 6, "max": 12, "chance": "1/30", "noted": True},
        {"item": "Manta Ray", "min": 1, "max": 4, "chance": "1/3"},
        {"item": "Manta Ray", "min": 2, "max": 8, "chance": "1/20", "noted": True},
        {"item": "Dragon scimitar", "min": 1, "max": 1, "chance": "1/250"},
        {"item": "Dragon platelegs", "min": 1, "max": 1, "chance": "1/400"},
        {"item": "Dragon boots", "min": 1, "max": 1, "chance": "1/400"},
        {"item": "Abyssal Whip", "min": 1, "max": 1, "chance": "1/500"},
        {"item": "Ancient Emblem", "min": 1, "max": 1, "chance": "1/300", "noted": True},
        {"item": "Air rune", "min": 10, "max": 40, "chance": "1/3"},
        {"item": "Water rune", "min": 10, "max": 40, "chance": "1/3"},
        {"item": "Earth rune", "min": 10, "max": 30, "chance": "1/3"},
        {"item": "Fire rune", "min": 5, "max": 25, "chance": "1/4"},
        {"item": "Steel arrows", "min": 10, "max": 40, "chance": "1/3"},
        {"item": "Mithril arrows", "min": 5, "max": 20, "chance": "1/4"},
        {"item": "Adamant arrows", "min": 3, "max": 10, "chance": "1/6"},
    ],
    "hell": [ # >35
        {"item": "Dragon dagger", "min": 1, "max": 1, "chance": "1/50"},
        {"item": "Blood rune", "min": 40, "max": 180, "chance": "1/2"},
        {"item": "Manta Ray", "min": 2, "max": 6, "chance": "1/2"},
        {"item": "Manta Ray", "min": 4, "max": 12, "chance": "1/30", "noted": True},
        {"item": "Anglerfish", "min": 1, "max": 4, "chance": "1/3"},
        {"item": "Anglerfish", "min": 2, "max": 8, "chance": "1/20", "noted": True},
        {"item": "Dragon scimitar", "min": 1, "max": 1, "chance": "1/100"},
        {"item": "Dragon platelegs", "min": 1, "max": 1, "chance": "1/200"},
        {"item": "Dragon boots", "min": 1, "max": 1, "chance": "1/200"},
        {"item": "Abyssal Whip", "min": 1, "max": 1, "chance": "1/300"},
        {"item": "Ancient Emblem", "min": 1, "max": 1, "chance": "1/200", "noted": True},
        {"item": "Fire rune", "min": 10, "max": 50, "chance": "1/3"},
        {"item": "Earth rune", "min": 10, "max": 40, "chance": "1/3"},
        {"item": "Adamant arrows", "min": 10, "max": 40, "chance": "1/3"},
        {"item": "Rune arrows", "min": 3, "max": 15, "chance": "1/5"},
        {"item": "Dragon arrows", "min": 1, "max": 5, "chance": "1/10"},
    ],
}